# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_m_dialog(object):
    def setupUi(self, m_dialog):
        m_dialog.setObjectName("m_dialog")
        m_dialog.resize(1341, 751)
        m_dialog.setMinimumSize(QtCore.QSize(1341, 751))
        m_dialog.setMaximumSize(QtCore.QSize(1341, 751))
        self.label = QtWidgets.QLabel(m_dialog)
        self.label.setGeometry(QtCore.QRect(210, 90, 931, 91))
        self.label.setStyleSheet("color: rgb(247, 247, 238);\n"
"font: 36pt \"배달의민족 도현\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.a_input = QtWidgets.QPushButton(m_dialog)
        self.a_input.setGeometry(QtCore.QRect(460, 520, 421, 61))
        self.a_input.setMinimumSize(QtCore.QSize(421, 61))
        self.a_input.setMaximumSize(QtCore.QSize(421, 61))
        self.a_input.setAcceptDrops(False)
        self.a_input.setStyleSheet("font: 20pt \"배달의민족 도현\";")
        self.a_input.setCheckable(False)
        self.a_input.setChecked(False)
        self.a_input.setAutoRepeat(False)
        self.a_input.setAutoExclusive(False)
        self.a_input.setDefault(False)
        self.a_input.setObjectName("a_input")
        self.a_search = QtWidgets.QPushButton(m_dialog)
        self.a_search.setGeometry(QtCore.QRect(460, 620, 421, 61))
        self.a_search.setMinimumSize(QtCore.QSize(421, 61))
        self.a_search.setMaximumSize(QtCore.QSize(421, 61))
        self.a_search.setStyleSheet("font: 20pt \"배달의민족 도현\";")
        self.a_search.setObjectName("a_search")
        self.graphicsView = QtWidgets.QGraphicsView(m_dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1341, 751))
        self.graphicsView.setMinimumSize(QtCore.QSize(1341, 751))
        self.graphicsView.setMaximumSize(QtCore.QSize(1341, 751))
        self.graphicsView.setStyleSheet("background-image: url(:/image/KakaoTalk_20200920_123437693.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.label.raise_()
        self.a_input.raise_()
        self.a_search.raise_()

        self.retranslateUi(m_dialog)
        QtCore.QMetaObject.connectSlotsByName(m_dialog)

    def retranslateUi(self, m_dialog):
        _translate = QtCore.QCoreApplication.translate
        m_dialog.setWindowTitle(_translate("m_dialog", "Dialog"))
        self.label.setText(_translate("m_dialog", "서머너즈워 길/점령전 방덱 깨기"))
        self.a_input.setText(_translate("m_dialog", "공덱 입력"))
        self.a_search.setText(_translate("m_dialog", "공덱 찾기"))
import main_background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    m_dialog = QtWidgets.QDialog()
    ui = Ui_m_dialog()
    ui.setupUi(m_dialog)
    m_dialog.show()
    sys.exit(app.exec_())
