# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


monster = open('monster_list.txt', 'r', encoding = 'utf-8')
monster_list = []
for line in monster:
    monster_list.append(line.splitlines()[0])
monster.close()

class Ui_i_dialog(object):
    def setupUi(self, i_dialog):
        i_dialog.setObjectName("i_dialog")
        i_dialog.resize(1341, 751)
        i_dialog.setMinimumSize(QtCore.QSize(1341, 751))
        i_dialog.setMaximumSize(QtCore.QSize(1341, 751))
        self.graphicsView = QtWidgets.QGraphicsView(i_dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1341, 751))
        self.graphicsView.setMinimumSize(QtCore.QSize(1341, 751))
        self.graphicsView.setMaximumSize(QtCore.QSize(1341, 751))
        self.graphicsView.setStyleSheet("background-image: url(:/image/KakaoTalk_20200921_163222539.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.PUSH = QtWidgets.QPushButton(i_dialog)
        self.PUSH.setGeometry(QtCore.QRect(630, 570, 161, 51))
        self.PUSH.setObjectName("PUSH")
        self.label = QtWidgets.QLabel(i_dialog)
        self.label.setGeometry(QtCore.QRect(50, 180, 161, 51))
        self.label.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(i_dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 161, 51))
        self.label_2.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(i_dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 370, 161, 51))
        self.label_3.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(i_dialog)
        self.label_4.setGeometry(QtCore.QRect(710, 180, 161, 51))
        self.label_4.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(i_dialog)
        self.label_5.setGeometry(QtCore.QRect(710, 280, 161, 51))
        self.label_5.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(i_dialog)
        self.label_6.setGeometry(QtCore.QRect(710, 370, 161, 51))
        self.label_6.setStyleSheet("font: 14pt \"배달의민족 도현\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(i_dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 110, 221, 51))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 36pt \"배달의민족 도현\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(i_dialog)
        self.label_8.setGeometry(QtCore.QRect(940, 110, 221, 51))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 36pt \"배달의민족 도현\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.WOD = QtWidgets.QComboBox(i_dialog)
        self.WOD.setGeometry(QtCore.QRect(630, 520, 161, 22))
        self.WOD.setMouseTracking(False)
        self.WOD.setEditable(False)
        self.WOD.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.WOD.setDuplicatesEnabled(True)
        self.WOD.setObjectName("WOD")
        self.WOD.addItem("")
        self.WOD.addItem("")
        self.RETURN = QtWidgets.QPushButton(i_dialog)
        self.RETURN.setGeometry(QtCore.QRect(1150, 680, 161, 51))
        self.RETURN.setObjectName("RETURN")
        self.D_LEADER = QtWidgets.QComboBox(i_dialog)
        self.D_LEADER.setGeometry(QtCore.QRect(220, 180, 361, 51))
        self.D_LEADER.setEditable(True)
        self.D_LEADER.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.D_LEADER.setDuplicatesEnabled(True)
        self.D_LEADER.setObjectName("D_LEADER")
        self.D_LEADER.addItems(monster_list)
        self.D_THIRD = QtWidgets.QComboBox(i_dialog)
        self.D_THIRD.setGeometry(QtCore.QRect(220, 370, 361, 51))
        self.D_THIRD.setEditable(True)
        self.D_THIRD.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.D_THIRD.setDuplicatesEnabled(True)
        self.D_THIRD.setObjectName("D_THIRD")
        self.D_THIRD.addItems(monster_list)
        self.D_SECOND = QtWidgets.QComboBox(i_dialog)
        self.D_SECOND.setGeometry(QtCore.QRect(220, 280, 361, 51))
        self.D_SECOND.setEditable(True)
        self.D_SECOND.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.D_SECOND.setDuplicatesEnabled(True)
        self.D_SECOND.setObjectName("D_SECOND")
        self.D_SECOND.addItems(monster_list)
        self.A_SECOND = QtWidgets.QComboBox(i_dialog)
        self.A_SECOND.setGeometry(QtCore.QRect(870, 270, 361, 51))
        self.A_SECOND.setEditable(True)
        self.A_SECOND.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.A_SECOND.setDuplicatesEnabled(True)
        self.A_SECOND.setObjectName("A_SECOND")
        self.A_SECOND.addItems(monster_list)
        self.A_THIRD = QtWidgets.QComboBox(i_dialog)
        self.A_THIRD.setGeometry(QtCore.QRect(870, 360, 361, 51))
        self.A_THIRD.setEditable(True)
        self.A_THIRD.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.A_THIRD.setDuplicatesEnabled(True)
        self.A_THIRD.setObjectName("A_THIRD")
        self.A_THIRD.addItems(monster_list)
        self.A_LEADER = QtWidgets.QComboBox(i_dialog)
        self.A_LEADER.setGeometry(QtCore.QRect(870, 170, 361, 51))
        self.A_LEADER.setEditable(True)
        self.A_LEADER.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.A_LEADER.setDuplicatesEnabled(True)
        self.A_LEADER.setObjectName("A_LEADER")
        self.A_LEADER.addItems(monster_list)

        self.retranslateUi(i_dialog)
        QtCore.QMetaObject.connectSlotsByName(i_dialog)

    def retranslateUi(self, i_dialog):
        _translate = QtCore.QCoreApplication.translate
        i_dialog.setWindowTitle(_translate("i_dialog", "Dialog"))
        self.PUSH.setText(_translate("i_dialog", "등록"))
        self.label.setText(_translate("i_dialog", "LEADER : "))
        self.label_2.setText(_translate("i_dialog", "SECOND : "))
        self.label_3.setText(_translate("i_dialog", "THIRD : "))
        self.label_4.setText(_translate("i_dialog", "LEADER : "))
        self.label_5.setText(_translate("i_dialog", "SECOND : "))
        self.label_6.setText(_translate("i_dialog", "THIRD : "))
        self.label_7.setText(_translate("i_dialog", "상대 방덱"))
        self.label_8.setText(_translate("i_dialog", "내 공덱"))
        self.WOD.setItemText(0, _translate("i_dialog", "승"))
        self.WOD.setItemText(1, _translate("i_dialog", "패"))
        self.RETURN.setText(_translate("i_dialog", "돌아가기"))
import main_background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    i_dialog = QtWidgets.QDialog()
    ui = Ui_i_dialog()
    ui.setupUi(i_dialog)
    i_dialog.show()
    sys.exit(app.exec_())
